# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://studentperformanceregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_93534fa222314a7380571e490f3d0bd8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cb9f8b1e69ec4f248b228f19b8ebdae8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: studentperformanceregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_93534fa222314a7380571e490f3d0bd8 }}/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_63ddb925c5cc4191acd5ed1d1b36ea3b }}
        images: 'studentperformanceregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_93534fa222314a7380571e490f3d0bd8 }}/studentperformance:${{ github.sha }}'